# Generated by Django 4.0.3 on 2022-03-21 17:37

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('polls', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='choice',
            old_name='quiestion',
            new_name='question',
        ),
    ]
